;;! target = "x86_64"
;;! test = "clif"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; function u0:0(i64 vmctx, i64, i32, i32) fast {
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly gv0+8
;;     gv2 = load.i64 notrap aligned gv1
;;     gv3 = vmctx
;;     gv4 = load.i64 notrap aligned gv3+88
;;     gv5 = load.i64 notrap aligned checked gv3+80
;;     sig0 = (i64 vmctx, i32 uext, i32 uext, i32 uext) -> i32 uext system_v
;;     sig1 = (i64 vmctx, i32 uext, i32 uext) -> i32 uext system_v
;;     sig2 = (i64 vmctx, i32 uext) -> i32 uext system_v
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32, v3: i32):
;; @003b                               v4 = global_value.i64 gv3
;; @003b                               v5 = load.i64 notrap aligned v4+8
;; @0040                               v6 = uextend.i64 v2
;; @0040                               v7 = iconst.i64 0xffff_0001
;; @0040                               v8 = uadd_overflow_trap v6, v7, heap_oob  ; v7 = 0xffff_0001
;; @0040                               v9 = global_value.i64 gv4
;; @0040                               v10 = icmp ugt v8, v9
;; @0040                               v11 = global_value.i64 gv5
;; @0040                               v12 = iadd v11, v6
;; @0040                               v13 = iconst.i64 0xffff_0000
;; @0040                               v14 = iadd v12, v13  ; v13 = 0xffff_0000
;; @0040                               v15 = iconst.i64 0
;; @0040                               v16 = select_spectre_guard v10, v15, v14  ; v15 = 0
;; @0040                               istore8 little heap v3, v16
;; @0047                               jump block1
;;
;;                                 block1:
;; @0047                               return
;; }
;;
;; function u0:1(i64 vmctx, i64, i32) -> i32 fast {
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly gv0+8
;;     gv2 = load.i64 notrap aligned gv1
;;     gv3 = vmctx
;;     gv4 = load.i64 notrap aligned gv3+88
;;     gv5 = load.i64 notrap aligned checked gv3+80
;;     sig0 = (i64 vmctx, i32 uext, i32 uext, i32 uext) -> i32 uext system_v
;;     sig1 = (i64 vmctx, i32 uext, i32 uext) -> i32 uext system_v
;;     sig2 = (i64 vmctx, i32 uext) -> i32 uext system_v
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32):
;; @0049                               v4 = global_value.i64 gv3
;; @0049                               v5 = load.i64 notrap aligned v4+8
;; @004c                               v6 = uextend.i64 v2
;; @004c                               v7 = iconst.i64 0xffff_0001
;; @004c                               v8 = uadd_overflow_trap v6, v7, heap_oob  ; v7 = 0xffff_0001
;; @004c                               v9 = global_value.i64 gv4
;; @004c                               v10 = icmp ugt v8, v9
;; @004c                               v11 = global_value.i64 gv5
;; @004c                               v12 = iadd v11, v6
;; @004c                               v13 = iconst.i64 0xffff_0000
;; @004c                               v14 = iadd v12, v13  ; v13 = 0xffff_0000
;; @004c                               v15 = iconst.i64 0
;; @004c                               v16 = select_spectre_guard v10, v15, v14  ; v15 = 0
;; @004c                               v17 = uload8.i32 little heap v16
;; @0053                               jump block1(v17)
;;
;;                                 block1(v3: i32):
;; @0053                               return v3
;; }
