;;! target = "x86_64"
;;! test = "clif"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; function u0:0(i64 vmctx, i64, i32, i32) fast {
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly gv0+8
;;     gv2 = load.i64 notrap aligned gv1
;;     gv3 = vmctx
;;     gv4 = load.i64 notrap aligned gv3+88
;;     gv5 = load.i64 notrap aligned checked gv3+80
;;     sig0 = (i64 vmctx, i32 uext, i32 uext, i32 uext) -> i32 uext system_v
;;     sig1 = (i64 vmctx, i32 uext, i32 uext) -> i32 uext system_v
;;     sig2 = (i64 vmctx, i32 uext) -> i32 uext system_v
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32, v3: i32):
;; @003b                               v4 = global_value.i64 gv3
;; @003b                               v5 = load.i64 notrap aligned v4+8
;; @0040                               v6 = uextend.i64 v2
;; @0040                               v7 = global_value.i64 gv4
;; @0040                               v8 = iconst.i64 4097
;; @0040                               v9 = isub v7, v8  ; v8 = 4097
;; @0040                               v10 = icmp ugt v6, v9
;; @0040                               trapnz v10, heap_oob
;; @0040                               v11 = global_value.i64 gv5
;; @0040                               v12 = iadd v11, v6
;; @0040                               v13 = iconst.i64 4096
;; @0040                               v14 = iadd v12, v13  ; v13 = 4096
;; @0040                               istore8 little heap v3, v14
;; @0044                               jump block1
;;
;;                                 block1:
;; @0044                               return
;; }
;;
;; function u0:1(i64 vmctx, i64, i32) -> i32 fast {
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly gv0+8
;;     gv2 = load.i64 notrap aligned gv1
;;     gv3 = vmctx
;;     gv4 = load.i64 notrap aligned gv3+88
;;     gv5 = load.i64 notrap aligned checked gv3+80
;;     sig0 = (i64 vmctx, i32 uext, i32 uext, i32 uext) -> i32 uext system_v
;;     sig1 = (i64 vmctx, i32 uext, i32 uext) -> i32 uext system_v
;;     sig2 = (i64 vmctx, i32 uext) -> i32 uext system_v
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32):
;; @0046                               v4 = global_value.i64 gv3
;; @0046                               v5 = load.i64 notrap aligned v4+8
;; @0049                               v6 = uextend.i64 v2
;; @0049                               v7 = global_value.i64 gv4
;; @0049                               v8 = iconst.i64 4097
;; @0049                               v9 = isub v7, v8  ; v8 = 4097
;; @0049                               v10 = icmp ugt v6, v9
;; @0049                               trapnz v10, heap_oob
;; @0049                               v11 = global_value.i64 gv5
;; @0049                               v12 = iadd v11, v6
;; @0049                               v13 = iconst.i64 4096
;; @0049                               v14 = iadd v12, v13  ; v13 = 4096
;; @0049                               v15 = uload8.i32 little heap v14
;; @004d                               jump block1(v15)
;;
;;                                 block1(v3: i32):
;; @004d                               return v3
;; }
